# Generated by Django 5.1 on 2024-09-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('date_fin_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('cv', models.FileField(upload_to='candidats/cv/')),
                ('lettre_motivation', models.FileField(upload_to='candidats/lettres/')),
                ('date_candidature', models.DateField(auto_now_add=True)),
                ('etape_processus', models.CharField(choices=[('Candidature reçue', 'Candidature reçue'), ('Entretien', 'Entretien'), ('Test technique', 'Test technique'), ('Offre envoyée', 'Offre envoyée'), ('Rejeté', 'Rejeté')], default='Candidature reçue', max_length=50)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.poste')),
            ],
        ),
    ]
