# Generated by Django 5.1 on 2024-09-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recrutement.poste'),
        ),
    ]
