# Generated by Django 5.1 on 2024-09-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_alter_candidat_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_candidature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='etape_processus',
            field=models.CharField(blank=True, choices=[('Candidature reçue', 'Candidature reçue'), ('Entretien', 'Entretien'), ('Test technique', 'Test technique'), ('Offre envoyée', 'Offre envoyée'), ('Rejeté', 'Rejeté')], max_length=50, null=True),
        ),
    ]
