# Generated by Django 5.1 on 2024-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_alter_candidat_date_candidature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='entretien_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
