# Generated by Django 5.1 on 2024-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_candidat_entretien_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='entretien_heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
