# Generated by Django 5.1 on 2024-09-01 14:37

from django.db import migrations

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('accueil', 'Permission')
    permissions = [
        {'nom': 'Acces au Tableau de bord ', 'code': 'Tableau de bord'},
        {'nom': 'Acces a la gestion des utilisateurs', 'code': 'utilisateur'},
        {'nom': 'Acces au gestion des employe', 'code': 'employe'},
        {'nom': 'Acces au Calendrier', 'code': 'Calendrier'},
        {'nom': 'Acces au Recrutement', 'code': 'Recrutement'},
        {'nom': 'Acces au Présences', 'code': 'Présence'},
        {'nom': 'Acces au Absences', 'code': 'Absences'},
        {'nom': 'Acces au Congés', 'code': 'Congés'},
        {'nom': 'Acces au Formations', 'code': 'Formation'},
        {'nom': 'Acces au Portail DRH', 'code': 'Portail DRH'},
        {'nom': 'Acces au Portail chef de département', 'code': 'Portail CD'},
        {'nom': 'Acces a la Paie', 'code': 'Paie'},
        {'nom': 'Acces au Données de l\'entreprise', 'code': 'Données'},
        {'nom': 'Acces au Portail employé', 'code': 'Portail employé'},
        # Ajoutez d'autres permissions ici
    ]

    for perm in permissions:
        Permission.objects.create(**perm)

class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
