# Generated by Django 5.1 on 2024-09-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accueil.utilisateur')),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('nationalite', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('poste', models.CharField(max_length=100)),
                ('departement', models.CharField(choices=[('RH', 'Ressources Humaines'), ('IT', 'Informatique'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('VTE', 'Ventes')], max_length=3)),
                ('date_debut', models.DateField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD')], max_length=3)),
                ('date_fin_contrat', models.DateField(blank=True, null=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_travail', models.CharField(max_length=50)),
                ('nbr_jours_conges_AN', models.PositiveIntegerField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents/cvs/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='documents/lettres_motivation/')),
                ('contrat_travail', models.FileField(blank=True, null=True, upload_to='documents/contrats_travail/')),
                ('certificats_diplomes', models.FileField(blank=True, null=True, upload_to='documents/certificats_diplomes/')),
            ],
            bases=('accueil.utilisateur',),
        ),
        migrations.CreateModel(
            name='DemandeConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('Annuel', 'Annuel'), ('Maladie', 'Maladie'), ('Autre', 'Autre')], max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='En attente', max_length=20)),
                ('date_approbation_chef', models.DateField(blank=True, null=True)),
                ('date_approbation_drh', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('vue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.utilisateur')),
            ],
        ),
    ]
