# Generated by Django 5.1 on 2024-09-09 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_absence_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconges',
            name='date_demande',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
