# Generated by Django 5.1 on 2024-09-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_remove_formation_date_demande_formation_date_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('nombre_jours', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='demandeconges',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.typeconge'),
        ),
    ]
