# Generated by Django 5.1 on 2024-09-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_sondagesatisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employe',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='salaire',
        ),
        migrations.AddField(
            model_name='employe',
            name='categorie',
            field=models.CharField(choices=[('CADRE', 'Cadre'), ('AUTRE_CATEGORIES', 'Autre_categories')], default='CADRE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='mode_paiement',
            field=models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECE', 'Espèces')], default='VIREMENT', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='nombre_enfants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_cnss',
            field=models.CharField(default='N0000023467', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='numero_compte',
            field=models.CharField(default='2345789016', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='prime_anciennete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='sursalaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employe.departement'),
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='employe.departement')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employe.fonction'),
        ),
    ]
