# Generated by Django 5.1 on 2024-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_departement_remove_employe_poste_and_more'),
        ('paiement', '0002_avantageennature'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='avantages_en_nature',
            field=models.ManyToManyField(blank=True, to='paiement.avantageennature'),
        ),
    ]
