# Generated by Django 5.1 on 2024-10-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_employe_avantages_en_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='heures_travail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nbr_jours_conges_AN',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
