# Generated by Django 5.1 on 2024-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_employe_heures_travail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='nbr_jours_conges_AN',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
