# Generated by Django 5.1 on 2024-09-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0007_departement_remove_employe_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('plafond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeIndemnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('somme_percue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe.employe')),
                ('indemnite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiement.indemnite')),
            ],
        ),
    ]
